# Generated by Django 4.2.14 on 2024-08-10 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=300)),
                ('sender_email', models.CharField(max_length=254)),
                ('sender_title', models.CharField(max_length=200)),
                ('sender_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 'Hidden'), (1, 'Shown')], default=0)),
                ('update_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
