# Generated by Django 4.2.14 on 2024-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0003_message_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
