# Generated by Django 4.2.14 on 2024-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruction', '0004_information_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority Display Order'),
        ),
    ]
